name: Roblox Asset Automation

on:
  repository_dispatch:
    types: [trigger_upload]

jobs:
  upload_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Requests
        run: pip install requests

      - name: Run Upload Script
        env:
          ROBLOX_API_KEY: ${{ secrets.ROBLOX_API_KEY }}
          GITHUB_EVENT_PAYLOAD: ${{ toJson(github.event) }}
        run: python bulk_upload.py

      - name: Run Upload Script
        env:
          ROBLOX_COOKIE: ${{ secrets.ROBLOX_COOKIE }}
          GROUP_ID: ${{ secrets.GROUP_ID }}
          RBX_API_KEY: ${{ secrets.ROBLOX_API_KEY }}
          ASSET_ID: ${{ github.event.client_payload.asset_id }}
          WEBHOOK_URL: ${{ github.event.client_payload.discord_webhook }}
        run: |
          
          if [ -f "bulk_upload.py" ]; then
            python bulk_upload.py
          else
            echo "‚ùå Erro: File bulk_upload.py not found in the repository!"
            exit 1
          fi

      - name: Run Upload Script
        env:
          RBX_API_KEY: ${{ secrets.ROBLOX_API_KEY }}
        run: python bulk_upload.py
